FROM public.ecr.aws/lambda/nodejs:14

LABEL org.opencontainers.image.source https://github.com/jeremychauvet/docker-images
LABEL org.opencontainers.image.authors Jeremy Chauvet

# Install basics deps.
RUN yum install zip -y
